version: '3.3'
services:
  redis:
    image: redis:7.0.0
    container_name: dcompose_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - docker-project
  postgres:
    image: postgres:14.2
    container_name: dcompose_postgres
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=/run/secrets/pgdb_password
      - POSTGRES_DB=${PG_DATABASE}
      - DATABASE_HOST=${PG_HOST}
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - docker-project
    secrets:
      - pgdb_password
  web:
    build: .
    container_name: dcompose_app
    #restart: always
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - docker-project
networks:
  docker-project:
    driver: bridge
volumes:
  pg_data:
  redis_data:
secrets:
  pgdb_password:
    file: ./pgdb_password.txt