version: '3.9'
services:

  redis:
    image: redis:7.0.0
    container_name: container_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    networks:
      - project

  postgres:
    image: postgres:14.2
    container_name: container_postgres
    restart: always
    env_file:
      - '.env'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=/run/secrets/pgdb_password
      - POSTGRES_DB=${PG_DATABASE}
      - DATABASE_HOST=${PG_HOST}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    networks: 
      - project
    secrets:  
      - pgdb_password

  web:
    build: .
    container_name: container_app
    env_file:
      - '.env'
    volumes:
      - .:/code
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - redis
    networks:
      - project

networks:
  project:
    driver: bridge

volumes:
  postgres:
  redis_data:

secrets:
  pgdb_password:
    file: ./pgdb_password.txt